#
# This is only an example configuration. Please see the Rails
# documentation for more details.
#

development:
  adapter: mysql2
  database: radiant_dev
  username: root
  password:
  # socket: /tmp/mysql.sock

test: &TEST
  adapter: mysql2
  database: radiant_test
  username: root
  password: 123456789
  # socket: /tmp/mysql.sock

production:
  adapter: mysql2
  database: radiant_live
  username: root
  password: 123456789
  # socket: /tmp/mysql.sock

cucumber:
  <<: *TEST